# Generated by Django 4.1.3 on 2023-05-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta',
            field=models.ManyToManyField(default='None', related_name='encuesta', to='encuestas.pregunta'),
        ),
    ]
