# Generated by Django 4.1.3 on 2023-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_encuesta_pregunta_encuesta_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuestas',
            field=models.ManyToManyField(default=None, related_name='pregunta', to='encuestas.respuestaposible'),
        ),
    ]
