# Generated by Django 4.2.1 on 2023-05-29 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_respuestadecliente_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestadecliente',
            name='pregunta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='respuestasDeCliente', to='encuestas.pregunta'),
        ),
        migrations.AlterField(
            model_name='respuestadecliente',
            name='encuesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='respuestasDeCliente', to='encuestas.encuesta'),
        ),
    ]
