# Generated by Django 4.2.1 on 2023-05-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_respuestadecliente_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='respuestasDeEncuesta',
            field=models.ManyToManyField(blank=True, default=None, related_name='llamada', to='encuestas.respuestadecliente'),
        ),
    ]
