# Generated by Django 4.2.1 on 2023-05-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_alter_llamada_respuestasdeencuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamada',
            name='cambioEstado',
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='llamada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cambioEstados', to='encuestas.llamada'),
        ),
    ]
