# Generated by Django 4.2.1 on 2023-05-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_remove_llamada_cambioestado_cambioestado_llamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cambioEstado', to='encuestas.estado'),
        ),
        migrations.AlterField(
            model_name='cambioestado',
            name='llamada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cambioEstado', to='encuestas.llamada'),
        ),
    ]
